# -*- coding: utf-8 -*-
"""
Created on Wed Oct 31 10:31:10 2018

@author: student
"""

import random
import time
choices=["I DONT ANSWER WEIRDOS","DEFINITELY",
         "NO MEANS NOOOOO","HELL YEAH!","MY SOURCES SAY YOU ARE WRONG",
         "MY SOURCES SAY YOU ARE RIGHT THAT MEANS THAT I SHOULD CHANGE MY SOURCE",
         "ASK AGAIN WITH MORE CONCENTRATION YOU NIGG*R","NAHI DUNGI","JESUS IS ALWAYS THE ANSWER",
         "POODIEPIE IS BESHT","NYET","SI","DONT ASK QUESTIONS WHOSE ANSWERS WILL SCAR YOU",
         "BETA ABHI TUM CHOTE HO YEH SAB JAAN NE KE LIYE","YOU SHOULD IMPROVE YOUR QUESTION ASKING SKILLS.","IDK","AFFIRMATIVE"
         ,"WHAT SORT OF A DUMB PERSON ASKS SUCH A QUESTION....OFC","U R THE REASON INDIA IS CONSIDERED A 3RD WORLD COUNTRY"]
roasts=["U R THE REASON INDIA IS CONSIDERED A 3RD WORLD COUNTRY  ","UR MAMA SO POOR, SHE CANT EVN PAY ATTENTION ","*KEEPS MIRROR IN FRONT OF USER*",
        "UR ASS MUST BE SO JEALOUS OF ALL THE SH!T THAT COMES THROUGH UR MOUTH","IF LAUGHTER IS THE BEST MEDECINE,UR FACE MUST CURING THE WORLD","UR FAMILY TREE MUST BE A CACTUS COZ EVERYONE ON IT IS A PRICK"
        ,"UR BIRTH CERTIFICATE IS AN APOLOGY LETTER FROM THE CONDOM FACTORY","U R LIVING PROOF THAT EVN GOD ISNT PERFECT AND MAKES MISTAKES",
        "U MUSTVE BEEN BORN IN AN EXAM HALL COZ THATS WHERE LOTS OF PEOPLE MAKE MISTAKES ","THE ONLY WAY U WILL EVR GET LAID IS IF U CRAWL UP A CHICKEN'S ASS AND WAIT",
        "U R AN OXYGEN THIEF ","THEY SAY OPPOSITES ATTRACT SO I HOPE U MEET SOMEONE WHO IS INTELLIGENT, GOOD LOOKING AND WELL-CULTURED",
        "YOU HAVE DIARRHEA OF THE MOUTH AND CONSTIPATION OF SMARTNESS ","LAST TIME I SAW SOMETHING LIKE U, I FLUSHED IT","IF U REALLY SPOKE UR MIND, U WILL BE SPEECHLESS","JUST COZ U HV ONE DOESNT MEAN U HV TO BE ONE"]
while True:
    y=input('ASK THE MIGHTY 8 BALL ANY QUESTION:')
    if y=='roast me':
        for i in range(0,2):
            print('Shaking...')
            time.sleep(1)
        for i in range(0,1):
            print('All the best')
            time.sleep(1)
        print(random.choice(roasts))
    else:
        for i in range(0,3):
            print('Shaking...')
            time.sleep(1)
        print(random.choice(choices))
























































